apiVersion: v1
kind: Secret
metadata:
    name: samba-auth
    namespace: samba
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:98NaHgo=,iv:hcgAqDjItUvqmndim7dN+ZgcuMOQsi3LllV3i9iRhOc=,tag:iipiKydn71p7XdaEZpplFw==,type:str]
    password: ENC[AES256_GCM,data:3iZSas5d8QQN0gk=,iv:BxAF13/e3vGaY9fc5CWvLHXAha8O8Ctff6s1QnpAmKs=,tag:Ew92nmQg0/oexkRJzepbAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZmMzM21mNEFKMTRBbkMz
            NUIxaG1oQjU5ejhJL0JhaFhyR203Q0JYa2dJCmtTRHFIOW4xcnJBUzdIa3VobUFS
            aXhwSXUxdWh5Z1ZqVnBWZGJYb0VGVTAKLS0tIDE5YTNURFRqOUdoMkVYZjlJWkRu
            NU1WNG56K3pNdzVMYkIrN3hwb05KMk0KI08yZgumLHB0CLjGab68rU8+u2e57GsV
            faRXCz6M54CBjM56RktAwgnO5xuB8sSL/QDpZ8PQEcDbaa11h96J2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T21:23:51Z"
    mac: ENC[AES256_GCM,data:gTEQyrSMMRvUVoKFTcyHm8Hw8Ey1EdBfG8VnzkohPsy2U4gpENc+4Z8p9nz8Y7MEuGJDifOCQtFSgBu7hoEDlCY6byZJcn5zzJruzGOAbbpBhartPqiCvU0is3ia8ixUB+TYGAqaoS8NwxrwbZ44SYEYQgmE6MoaFlcXX+Z9/aI=,iv:O/7nBnQdo1YCn+du/JvEJ/OZ8j7Vi+5B60CF2Y6e9JA=,tag:dLuVUXazyW2YeOO9h/nD9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
