apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets/gluetun-secret.yaml
  - lidarr.yaml
  - lidarr-ingress.yaml
  - prowlarr.yaml
  - prowlarr-ingress.yaml
  - qbittorrent.yaml
  - qbittorrent-ingress.yaml
