apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: lidarr
spec:
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: lscr.io/linuxserver/lidarr:nightly
        ports:
        - containerPort: 8686
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Rome"
        volumeMounts:
        - name: lidarr-config
          mountPath: /config
        - name: media-storage
          mountPath: /media
      volumes:
      - name: media-storage
        hostPath:
          path: /mnt/das-storage
      - name: lidarr-config
        hostPath:
          path: /mnt/das-storage/lidarr/config
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr-service
  namespace: lidarr
spec:
  selector:
    app: lidarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8686
