apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: lidarr
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:c1WMxzheA09b,iv:DksaT1UyCCRc6IlRpElAT30tnJRMPnZslWgZkwTW8Xs=,tag:WbXMKV0PtuM9riBDlBpaDA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:guJqy9GiR5js,iv:ojITXEwvjFuVFHYJzSEjcrDZvOcDPtwPo+bqpmFuSm0=,tag:WIWNE733/5u1aotyqXvIDw==,type:str]
    #ENC[AES256_GCM,data:mTa7ODfE98z0CF0i6V2FjWUR0JFh37xvG/6RWZy/EKuqtKoWHcm2M27zb9s59jkXWhFx4fzMH4iQK96ZtXvcbw3mgCLQ2jIZ,iv:+tEz+8JGpDLNE1vmaK+Ym+VVRZLo12RDfIuHtkHh2z4=,tag:NWd1x95mlmzFe4KGzXycOw==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ExDuFTbhw8Q3S6DbVB+sAsrJt4NvgRqJKKCe91RFSbruHWZMW8TYDiQRANc=,iv:cOnvghUSxb22XtSVDmpmW3fylfKeB6bcY1kJ8C6BS6E=,tag:XK84RcOLQr+lCFNZFdQiNw==,type:str]
    #ENC[AES256_GCM,data:eKfqGKBwwfsJww57SdjfkDcLOiGL1UYa05lbAj3ugoEsGSKVmW9BxlaMKbcZPNa/nixu7qJwsdZdehzGuOkgmwJte/NbXFrpwE8ncbtQgHW/9jc+4UVN+J6Al6DAWL0Z,iv:OrbyUzraiGWAy96735tV9QpyU0qwBSReydViKvP1e+s=,tag:9mws6TCu47TmML/iYjA7IQ==,type:comment]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:cgJwcF4anovQPhE=,iv:S8Z1n4eO01kFZ+cqBvJqLbFKAUHI4n+ep59ZZk+I1ws=,tag:Dgdu0ti3LAffS+ItXfR9RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ1pSeUdBcVJmdkVUa3Bn
            VFU3emVHSCtYSUVpMWxCb0E4RkhpVkVzazJBClFhUDRPTGQ5Vm1KdjdmZk9scWN2
            SkNMb0lzc1Z4L1FRN2p4SE9PTWIrVlUKLS0tIEpNelE5MlNZOGRMMHdFYlNmbnhh
            YTJ3aW51RURnMVpzTWpUWlpwcy9oUncKYO4UnoyTAFdwov1dB32YsSSWOdmMRUzM
            Y7EuTqfGdHcA/9NSoevK1m1XP7Z+dumTy7apbGg+Ml/ih3qN3ARCsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T23:30:36Z"
    mac: ENC[AES256_GCM,data:kyMGuJji6X0B9L/MPhLEcSov+/QmDMAD9IdiRFIrdu9gJzY2twqWyvbN4CGkR//QPgKRASMzBeGmM+H3tOKEXFZJ6KvYz1Nklpzs9b+2t/wdhZ43v17IgHw0rh6Nh+YYx1erSruWqu6MN2nI56VUdretYK/mpYHNKN9ZSzF8f7g=,iv:ZzSqxRX4+fX4KjORVrzn7Ur8lZzS/zacF8rWybwmTAM=,tag:Q8EQDnxQZLLXPWLqvvc3Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
