apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      hostNetwork: true
      containers:
        - name: samba
          image: dperson/samba:latest
          env:
            - name: SMB_USER
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: username
            - name: SMB_PASS
              valueFrom:
                secretKeyRef:
                  name: samba-auth
                  key: password
          args:
            - "-s"
            - "roms;/mnt/roms;yes;no;yes;all;none;all;Roms"
            - "-u"
            - "$(SMB_USER);$(SMB_PASS)"
            - "-g"
            - "force user = root"
          ports:
            - containerPort: 139
            - containerPort: 445
          volumeMounts:
            - name: storage
              mountPath: /mnt/roms
      volumes:
        - name: storage
          hostPath:
            path: /mnt/das-storage/filebrowser/rom-storage
            type: DirectoryOrCreate
