apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:D5XJlhS9F+6DIw9SR1la8vtcd/3qjZhp,iv:guwxHvWBv6RVdOpk+gsAj1QYIo5biYou6VpQnksOtcQ=,tag:3pAWJihhDQhYi1ZAPO+ddg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:BFXpB09EzhKnBznQC23OvkLgZJn4UiiDWH1nUvtpJcM=,iv:9lM7NYwpsECU8u29UtkSsaLYB9Pue2WXxjZFuSq5Glw=,tag:krfPT6Y3h2rsfRvY3fI/oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQUJXUklJckU0bG5oalVU
            ODlaTkRFUGdqdkNDbjhOaFR2K3B0TmZCRVVFCmpVUW1VNXRHNi9rVE5HUmtEazBw
            cnFtRDEwRUQ5eFI0T0lEcDFYSGhnbDAKLS0tIDhxSDhRYSs4Qmd5NmNMdlBIWkNO
            OVFoMVZlNys1Vm1qYzFYL2d1aUZVcTQKlE1mYWeWveaxZnVFrKBIRcZqK6+40T7v
            repE4CBUtfM9RGeBd5m2IJRyEjnVzUxDbfwKFczZKHauwhAAwf+/IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T15:34:37Z"
    mac: ENC[AES256_GCM,data:h8Yg+lbYAMnwiCkOMON4GAUi0e3/kuK+J8hKiNFW0mOVsOqfsUZn/g96FD0ZkJdyAFxHNBZUAQx+WnRR3OMwX3sAERgtyLcTxS8lNEd+TKLrruLmWBwx+aChnIaIQaH/xEVC0m2cKtXyAFIgftIZQfSeFdGy5VQy1cRyDZoaCLE=,iv:E88gDU+upkNZ1UEOe4LzUNUoesSSdAXIsUuFdIwpbdc=,tag:bMtdxst6tUxmBZpDDToYqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
