apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-ingress
  namespace: music-server
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - navidrome
    - deemix
  rules:
  - host: navidrome
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: navidrome-service
            port:
              number: 80
  - host: deemix
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deemix-service
            port:
              number: 80
