apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: music-server
spec:
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
    spec:
      containers:
      - name: metube
        image: alexta69/metube:latest
        ports:
        - containerPort: 8081
        env:
        - name: DOWNLOAD_DIR
          value: /downloads
        - name: AUDIO_DOWNLOAD_DIR
          value: /downloads
        - name: COOKIES_FILE
          value: /app/cookies.txt
        - name: YTDL_OPTIONS
          value: '{"nocheckcertificate": true, "quiet": false, "no_warnings": false, "source_address": "0.0.0.0", "cookiefile": "/app/cookies.txt"}'
        volumeMounts:
        - name: music-data
          mountPath: /downloads
        - name: cookies
          mountPath: /app/cookies.txt
          subPath: cookies.txt
      volumes:
      - name: music-data
        persistentVolumeClaim:
          claimName: music-pvc
      - name: cookies
        secret:
          secretName: metube-cookies
---
apiVersion: v1
kind: Service
metadata:
  name: metube-service
  namespace: music-server
spec:
  selector:
    app: metube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
