apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
  namespace: music-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotdl-config-pvc
  namespace: music-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
