apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth-values
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:1I180dIfMkyXutlG88gPvHRjbyUkp2DK3KdehhI3s63e5JcFH9/RTE2v1FBXw9tSoaR45SKQgahXayavpYEUrjN0t5fy,iv:6nwDm0/6uA273WiXw0IQSpqS3pAdL0qMUc4obMggTqQ=,tag:f5SLUrHLPBs0mPBH+2v3Zg==,type:comment]
    #ENC[AES256_GCM,data:2n/cVtue7BaVQ6WrjA3hMWu62LygRD3NtUf8wNFwMJ4kmnFJI6tbllc5VquE/hGlSX30U79jo5t+EICW1W17myr5CzBh3cHl,iv:VBpG0ygG75hfKct+QfEgHILCf8b7OP1sr5Qow0WxqNo=,tag:e8RFb/Ef7W4ym00JiGtaKg==,type:comment]
    values.yaml: ENC[AES256_GCM,data:kfEeAdqw5DiAVFAwjLoWvqooIVMzNTXxGBiD0hvlM5Dn9aDBStXwX0IYotq+jqnqwQCcVug0NVxroQB0D0ZqjOwnSnVYXek6lQXgSN+SVZRht7SjBzuy+bR/dpn2VGFWmBhepEckpn6ILCJeBDMxPeDvM8K7NT6C9A==,iv:tJ4NZKAvl+jxNgYCZKZFfUAoTglfUT5ZYAuwIR+M1hk=,tag:eUtXS2HCuoovQRoxCuoWdA==,type:str]
sops:
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydThQZVhNNjQ1OFJZVXpK
            S0Q0Z2VYNVdqN1c5QlA3TXFOdmtOa3AzNDFvCndjRnl4TGxiRXdvMnRZQnQxTTF4
            SEZWNTN0MzhGN0N6UzlUUWdJNEZmOE0KLS0tIHh4WEsweVFHTEk2Z1laUzVmL2ow
            ZXJBUVM4MzUrbjZESTBiL1p3YmpjNFkKdQCXW0M+hJjniLVmBpOD3vya9OrnmRYJ
            iVS1U4SvjQFiNU2cF5DYjgJyjdUZV+BE79zU8BiINPmnEN36XmVUeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:04:36Z"
    mac: ENC[AES256_GCM,data:kQQ2ZbL1/3jXacbNBRmNGYaXVkgEK6FI+msWxUTAaqtNngFcmtQBZAUkLQcc5iW5VxaYSlzKPwT6pN1iueTgflDdbZSwiR+kHEAsjqIEqd1mcfDp6q7rfxrFsbcN2wX/a+R2vx0fsu8Ny1Vcs0EsLDWzgefu93tgADyXffH5Htg=,iv:hNfPiUlkxpKD1IDjF/5Dz0hOHcXl94CBWQyF51iWwwc=,tag:xCtyWY3SDvjGCCA864UFuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
