apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">= 58.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      dashboards:
        default:
          k8s-cluster-summary:
            gnetId: 10856
            revision: 1
            datasource: Prometheus
          k8s-views-global:
            gnetId: 15757
            revision: 1
            datasource: Prometheus
          k8s-cluster-monitoring:
            gnetId: 315
            revision: 1
            datasource: Prometheus
          dashboard-15282:
            gnetId: 15282
            revision: 1
            datasource: Prometheus
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: 'default'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      persistence:
        enabled: true
        storageClassName: das-storage
        existingClaim: grafana-pvc
    prometheus:
      prometheusSpec:
        retention: 15d
        retentionSize: "45GB"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: das-storage
              volumeName: prometheus-pv
              resources:
                requests:
                  storage: 50Gi
