apiVersion: v1
kind: Secret
metadata:
    name: seafile-secret
    namespace: seafile
type: Opaque
stringData:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:pGiuYZN68mPP7ExJNbjT42ymVxHRG1DwmD5g03qzLHFLYesYYsI9/w==,iv:oJ78YVJ11w2TAjV6fG5wkIqWeNXFc+NOtef1LAbAKAE=,tag:vhdHYNWwUKhvILv+QM5Nsg==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:R0+umF96+VJ3zc5rvJChGd7XHHRg2scRrNJ2BIDuQMFaK/Fxgcyp8g==,iv:LccUYPBFc3ghWDuy9XQWqoZLAvUyH67BvZQ4pl1x7Lw=,tag:d49qdmAHGIk5ssSjKPYxXA==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:sb1LxBr6yF3FMWZPkoWUL9pUgN5oWRRB8iYw/uVzeJ2LHom70BQNYg==,iv:5MtRGyynbsgvqmyVBdB1PKT5YJ4+zi9M9FBA7ytViuA=,tag:yKJ3xY1scIEHMUR2R13faw==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:sVq28PHwMMSpcaFA6WWWcfF5WIN7TMQb8TdnQe6i5AK1VzxmyDr48w==,iv:7BKpfvYiDKIqgdzGhRNfI3vb+73ODe541iyzY/FHJK4=,tag:m9l4fRL5AQ/ScXbVov4y6Q==,type:str]
    REDIS_PASSWORD: ""
    INIT_SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:32d6lVLiPQsCMmAUt5glRfAzjFzthRTj,iv:8UCnvAUD8mY+vXBpnwABI0w4EEUT46SGuPDLAzHSPH0=,tag:aelFDOXt7xLjh9rsd6nIpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeXNCaDE3R2lsNjBHdUl5
            SERZRUduV1Fid1NjVWhaYXpXNFdOK2E0VFhJCkoxaHJ2YU1ZUEdJN0JnQklQWFVm
            ZllUbVhoY0k0dStidVY2NDduMktGdGcKLS0tIFIzUkE0MFpSdFhIUnc0Z256S2o1
            WHF3eU5LTkNKYWl0ZWd4VlNTNll4dUEKK0ivAF2h23w2VdNQnGrJGhMAbwF6qlgS
            Yg1etcb++0wk1FxsFpVaDMZOKB9xgMfZHf/nMXij4jFsON9npaOpVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T11:38:27Z"
    mac: ENC[AES256_GCM,data:gOSAcWiC3aLyNf67I2rGvX184NHM4cRSxuyZHodIBDcitNWTlwInlSUrcJAa4+8/A+xbbVqtr1fH3LQ2ZfWxYhp3fC+UDSog3RJBOQ07xFAB7bsR27zksSgNtINoo8M6iD+2ZUVJftueAA+kcpgmaAUcqkNPNNdS3jHDnbf6ROo=,iv:8PfHdJGgCauL4rwoV6x71GkgESO0Z61ftkWRGMdiamE=,tag:bNac6QMmXrghyfAoOoGQVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
