apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:slCc7ggJB0aB8+s=,iv:8U7Vx1jaD3JKR8uv1xEjFAEKfI3Y+HyUmFpUio8gTWU=,tag:/fv86dsHAV9kFaOg9T7mSQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:psHE4bK42oWa4nZ5KjPB2miEZUGKwOjoF1MNP0FMvALnDE32dJVUVQ==,iv:S9WLWDNsDz6rYyBFqKlTn8fwqJj2hyhXm/TWpaw81hQ=,tag:D1+ALFcpuLQtJqbdDw9bfg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:QDG3fGQholYxb67hb0s=,iv:5bh4C8HClZQl6ZAeoZrrSlBjjUfVUNcbhMawyDKx2jw=,tag:g4uUpbrBO9zY3ugciMGeDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVTdIUWZadFVMbk94U3h0
            TG1tUlJjZnFObmJ6Nk1OT2tDZUxBa0gxQVRVCkkrZjY3dFJDczVWM1RNaG5Yd0pt
            NUkvVnJnVE1mN2ZHc0pyRHJ1bjEvdFUKLS0tIFRaWDMrcVljZnBMT0FWSnNyR29a
            dHJORWcyTDdkeW1kYnFVWEx2azdaUVkKNWSSbAJPBebTcY+j42/Ue1Ka7t+lvJ8Z
            +KjVWLNn+8aRGn45EHGn11dKyiUwt0LT+1aT4knVASFXj4LswH7tkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:49:19Z"
    mac: ENC[AES256_GCM,data:W7sRJU1Ky3wcchi8crPxA8jIuxSAIM5ldJYco9nodvYFWg3Q8ct40i6gjndi37E9xHIpxrH9fn+eb2DU6XcJZirTBWbNDuqA5G4l6L5duGw23HdEPl54rThr51TkSo8V22GOXNv/EOINJ7kDjhSNlB/npG5Op/fcKnQvdcMbB44=,iv:esmcHfgj106of05t/lUK/MxOKv/BKAHqvyZAD14UyZ4=,tag:yNJW3TZkgfv7Q0IMGlzCTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
