# IMPORTANT: This file contains cleartext passwords.
# Our .gitignore should already prevent it.
apiVersion: v1
kind: Secret
metadata:
    # The name k3s will use to identify this secret
    name: postgres-credentials
    namespace: tris-game
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gvUYrdRuUaavUb9fFArORsCfTeOFJBCcvoE=,iv:r+S5uSK+/S9BSkSQWRn5BIEFSHC9LwX+xKMB6zcC0Xg=,tag:5v1XOdfu7WjzIHAKFYTCJg==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:zPFm+lLuaQ9iClM=,iv:TXEwLAnXrXlv6t3f6sJzfNxJOEO2jH7w/R+F8Lv+e9w=,tag:Kb+hVJjdlnqLzho6Z4Hvkg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9NTHuE6OpRwe7ZdSJOoR5Tzq,iv:yHmHnDsXeJPxFMihC2f8V7zrnNyJnhMsw8rDWaE0e1I=,tag:/pxfNa6Nj4nkq+wEXqAqvw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Cwg0ypg08KFvbOFyAXY=,iv:hbtQmIDDsSJoa6K/F77A2cym89dBgeGEmQWUHoDhF20=,tag:1fAccp3+4Ml7TMhbvNW7AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMnhtMUFFY21rNUoranJO
            NythM1VVQlk1akE2bkFDVFB3RkhlbUdWVHg0Cm1TdG1SYVhWcGNQM1hEa0VzVzJ2
            OURuei9Pa2gzeDlGdnM3Qzl4cWhJRTAKLS0tIHJkZUZpSFBqcXNwc2NsbUZicmdE
            RjdkcHl4SHVZTk1RTVZoVTNpV2F2cUEKpuiMbtnh81Zh/e7tlo309GRCz4grpCaf
            2eFXu4laNhyb48ikMiOUkP1pzfK0U5/g+cLmFkbtyJhomWEHEbb2Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T15:49:27Z"
    mac: ENC[AES256_GCM,data:lfuR6riFwiu/FAUpNxhJXcc/wzIt5awcEDiSVfV8UZEcr1YIAfoysKVeyb1Q28VIcmFVRdsEatCXHEOKZq8xbNonf5IzpgwicLdfUdAAli0w7DJRJocGjmBtCItZGx83cKa+Ty5+LahkKQVP2uw5sgPayFoOnP3wMBCjhOdZXjM=,iv:ZCB8yP855Gxgm3k1cP6xPvFu0Iyh2aRuCAgge2Ybcjg=,tag:Ilxt4Rlh6UMnZgtB125NPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
