apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: tris-game
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ajyWYEkxviCw+Kw=,iv:biZ7NUpVRTPUmb1JclBAxpdMvr7PoQ8aRE+VbUqltJg=,tag:28Zv5/OdX0cBIospQjDM1Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5fh9F/Gp4cMnJ3foh0m2p7b8LewhznzaEpkYtKB5H3F2vTQ0xHSclg==,iv:2edfvFpYGE0I0d9891vOzgGE8/qZql1Deo2LLv0QULM=,tag:Nxh1Sz/rKqROyUjX6RXaHg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:K/xhO81cf9XlLfEwTPA=,iv:pOKtYn6Bu1BnfujlmhuT7r5/vVqv092kwZMj3qVPRpM=,tag:idWArBbxblpaf6wzJ7Jd4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMlZuc0NuWEZmVlVrN0Js
            ZnpWU2ZhLzdXUGRjbEJOUFNvd214U21KV0NVCmVMajcyUDR0S0x1LzVsN2x1eDFx
            QTNzcU9LcE9oQ0F2VDZRamJndndLcHcKLS0tIDhKVHhldkRLa0E0d0ZzQWY0MHZy
            cnRoNEQva0NFOGJZeGhmTTFVTW5FMDQKKZxVMtSyhdQ4H+da7tbHFjYbqH9XQ81D
            mjyqGL/an56vaK8FC4aYsk/0i33U5FueVCqECvV8KIokj22d9G4xQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T06:47:20Z"
    mac: ENC[AES256_GCM,data:+3rd3U2Di5vSJxCI+ggDBnDN10uVfs+YDdNicMYxUJ6T65S5C89xUrecCvkWBNneFs1WH1gvL/h8PYVz12gEdFHgeK5/RuOi8RoSokbrTHZyoS7VCI7MrvnUtAAQrXKJtVwS+w230n5kv6wDAe29UTI+JbE28Ciu9ZbpQmAtmqw=,iv:W3qsaaSt/AHWv4jgqnpEv9b110t1chLsCDNOggEmOi8=,tag:+BPUu27QAoree5gpXRSTRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
