apiVersion: ENC[AES256_GCM,data:nX8=,iv:KaguNnPa2+EmlLGg8l+cwLto5DP0pRdApjUzILlLgQA=,tag:ezk0RQbXQ0XoxaqrUcue5Q==,type:str]
kind: ENC[AES256_GCM,data:C426GCKo,iv:XxQw8k7G1uSWzJcyLpOrj0/81M3yK6xHZ/EG9U4TVKM=,tag:KWhGK8ASQa+xcMD8YwHHjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jdpkYg3WOr2QBXhbNqWhw9AjZ10=,iv:r36UrrAz8qqFK/Im58/z+d/1j8OPhBzXCRZyZiklhqA=,tag:hp9WSVbrl2eOppBVnoqR3w==,type:str]
type: ENC[AES256_GCM,data:/Cdk1+il,iv:EuGyLZHG58hGxLZaZsSWFWIfrLO8jQ76Y2fN1JDrYzw=,tag:WtwkN2D84fwSLny3rt5ONg==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:1M/jouJIfwc3+xM=,iv:JsTy8l6RVNPLnVGxw0pYJFEL7dtyyBqN734qm7SLt/A=,tag:dudtywK8YUVINGiOz4akag==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:S7S5lo4POKuyO+C3ONV4WVf0s2whMVdK,iv:ENRX4cdH+aLNbUAnOt12ursTm7bDAJZMb2+N8otu98I=,tag:7xKQfCkrfkqKf0SRWl3UBA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:NSoiiH4GXOxXFMIf1AA=,iv:xJzNQo6Os3Xdgk1lOZ2s+9LvV/GvbZBjyAKDIwgjHwY=,tag:M8OFpChsbhvZIzNQd0EB/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cjZaNHE2cXlLc0YwT0U3
            U2kyV0l0ekNMdWpqTUpRdTcyc21JK0tZajNVCm8zbGdLMFlRMThOcnJqbGpGN2E5
            ZjlWc2tJOVgwVUFoN3hER0NGZmYyQWsKLS0tIHUzeDlYbU1LeUNVZEplSndHNjZN
            VnVZcG03MndQTUFTUkp3RFk3QzJwWm8KI6jUK3xV8atbz2Xray1kKJv0yfV0lGjo
            GTz1XtKYZEHvvMc45olNbasvevii2Xqrg3hngpUM2tgeFrxHK1KkqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T15:49:20Z"
    mac: ENC[AES256_GCM,data:dn+ozM3JAesCkG58zQkYbHwbbbj06kR1qqfyjwS4pHYthhsrxpp0IwM8V8rT+fBTbW7sVlFFAkR6KuE/0XZV6O9QBNJ9jM8flXiI8GhS6HgtcvG5pdl7T3E5A4oS+tFispP9yUKM8wNl8KVIju4d078xMf8oUDZ5YlJAoAnphRY=,iv:Wgks7l5s2bdJ8jvHB3UXfGfmUeLr4Ara8TlgvzBdtAY=,tag:3espm/r+9uCMCNE6Dg2ttw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
