apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: das-storage
  hostPath:
    path: /mnt/das-storage/forgejo/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: das-storage
  volumeName: forgejo-data-pv
  resources:
    requests:
      storage: 10Gi
