apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: sunshine
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qQmBnUIC9bBV2hwHsMrw/yt2QcV07kpanXqLlKGyIurl/W1FCa9bRmlXGTA7jYcnUIKjeVvTnN95nok29kCRmyudl3+di8gBrE/K7v1KdoEwJnu7YbdBrwHX8JM4rD8mmUAHn92HYw99v+iJkizzGcsih+h6hYhwfVDtquIRIT6cwzwxYLPvzLS3hzNnocMvKkzyQINqa642mfa1OheDi5eSpjvxpdOscOIz1oAuDp0AdvptNXK9itg85bclP/t4GHu/OyWGMuy1dflgQDpte9wkcwRdwoSxQlGUMBm8iucD4DvDVPM7sMaeeqaDQ2GfRoPSaUakffD2aZnpiQ/4tCW+HHiXfxQcNcUwHEFhdoUlVXekTyw1JzBtVCeH1OCYjTjtkFQFjruosGFAYSMWZXyUqTH7WCPvVonLd/8alJdeacEJIJenrdKJzSxx7MT9rEYEPerh6VLZ+Cgc1LB2jXO+IAGSnA5t36+xORXuQk/tz/PIB5MERue+/PQkfS7fRdCL6PbdpB2i4GmHQzL5aujwFyUDUs7qqKOs4m0yYLoMV0V4PHABNtd7CoKpx8YDlhkPkqRVMO+pzuf/udEP7hq+G0+rcsMOXmx4zz6yHNL1/vwgZSAIqoXdLErtGSNZ2uv9o5D4B3k4R7DAGUJqBwIsSwdwfYxzqahiAiqEGbuSp1wX,iv:LbDoYSL+ZwWHCIf+ko8HFgIjkLfH2iIZ58HeWgfYCRw=,tag:gZbb10nqrYoHMxBXDDZN+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZGY0U3BpNkg5VEJZWHhJ
            RVZWcWg3RDBsc2NNLzIxZjhCS1dFRXRlTEF3CjRwbGQxY1NtamJNemlUb1d3eUxy
            M0RaQnBXOFRheWErcE1jNm5CV1orSlEKLS0tIEw5SGRhY1ZISm1Wb3FMMldIV2lO
            VjJ6eUJaUXdMR1pFdGNYdmw5MXNGMmcK8SnIacVmwojZ1KDygFPDCDqi9M+4qaD5
            JhxLTJ/zlyF5v0mpLzFiUb1Emlthejc8+uUTgPFsbTT9ivUQyWye/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T10:29:40Z"
    mac: ENC[AES256_GCM,data:pU82daoAeHryiDzy97T/3Zncrtl85xHas2G3LbTv3RRH15SkV88CkIyZ6ERKjoQL1xrxoI14LhjfFOIZaKRqzWrlt7cphoREc8m8n+C0jA6wCA/nPgxphCheA9/XQNDgs2wQ3kreeZrXmiXaffE7bU6JNBkZkyBaeJE54kNK6zQ=,iv:48eP4Je+USVNFYv9gvhtjNcwtsPXg/jh3A+waqmhDrM=,tag:Ek7f/YkdUSahN3dujmyPng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
