apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: sunshine
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ZcLcMA1DdyleY+0EEro/q+xU8Z6/Vpqdc5JjjSOaJiBoQeZZLMYudZEoUp9QCmM815qZT6RMaTw54ZIj2ss5Fq3Ag2c7+wB1bRsupPCoas0uEfQD6x1jh4/i2m+jqv5CkPVeYmDH4hLck5gJPTfqRjOHE7rLcwDIm7Mxj1/hn1JmDeVTicZYGOBdvfNKb7yvxrnaCF8id+gMKbJh+lW2s4w574mmNakO/z0ZnmkCqsqXeMwri2gNcItLHaU8eoP3EBGz/BldzPemvPCcOdayfvxEeiibDHiv4PbrSCLL+03rdFkhQ0wzLQcJ4fSTIHGKS11ouSAE7he/S/SguQkjyg==,iv:qlT4k9bi1M5IqTPsO49oLWzlGNeg6/g1vuTxcbqvN2k=,tag:1UhHzMbnKTYfFk52sWWd7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ2lHRUxtTG1SYjYrNkI1
            b2ZKbmZoc1diakJZK0UxT1VybFdMZURTemhBClZTWUJURDZHUUIyb1loYmVGT2pO
            V25uOS84ZVJTSUhiL0pRYncrVFFGSEkKLS0tIHMyUHNhQmFvQVBRekFITGIwN3pD
            TmI2SjBaSEdoZy84TjhCMkxMYndzencKr3wotRNUnHpkZQxxEM8xbbbz23R/OLtz
            ycYDiKhix1lVA3c/78odXVKqXxBzpeXqpxY3yHo9o0/1cePm/yYMkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T10:20:38Z"
    mac: ENC[AES256_GCM,data:qBlMlezvTFqUxzycaaG4Vapnf6fRkla+t2Ymmbr2y8rJunFpTIdmp2jq6Va2H/RwObAqVKZuElgFitcWolB+E38aPCAZYRO1wJLgwrjw4Yec93x7UMMemziLxMrHBui4E2nh+hiIID1eP4FypyJIl5PiAabZVJ51eF+qn+N08Cg=,iv:lABrn/tIvTV9uZ0tX+Nb9NRa+BmGJquQUfEmpn0C3Gk=,tag:J7n5KcdEFFNBvmQeZYttfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
