apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
    namespace: slskd
type: Opaque
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:ObE6hvo=,iv:rOgHBxYPGsvXOnOSRpJk04kXIcoGTpZDpih+kYw8omE=,tag:lkdx1js44jKGRemU1War4Q==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:LxqThe8=,iv:hsPmp3zZ3cZZY3lWvVdmDICXqwd0vchAYkLI6eNeH2I=,tag:bFRalZb0p9RLR7wWyX6t5w==,type:str]
    SLSKD_WEB__AUTHENTICATION__API_KEYS__LIDARR__KEY: ENC[AES256_GCM,data:yKcvFccysqjgzpYODNI3n+7J2keqTA==,iv:lgoHBk3JSXR992PxzS5ROjM8UrBX8JXI9+VMVYetc68=,tag:F4+Us36WZf0h1TpU1ogloA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OTIwZVM5UVg3VS9ITEc2
            ZHptUjlmZk04SGpmYnNnbWxQZ09vbEtPRG5JClFPclpRRnc1V0p1REtZdlhjWk1t
            S2t4NDR4V0cyWW80Rm04eGdubDVEdFkKLS0tIGI4eG81c0FRZmxxYlVvanRadW5h
            WGthb2JEWms1ZWxmL3N4R1YrS1U5UE0KBU+7w9J7RIoV2d5CeLhD9mgxV2PLAS+V
            jv0G6JkFt71RmpTPPHeItWEHL8BuNdXokO1KB2FE0HRo8wuoq554WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T16:46:19Z"
    mac: ENC[AES256_GCM,data:LZNzs6BT64HPfbFarvQd4+vxAYZnWg572vcCwgOZsdcTjJpnFl+sLuCgqhFDtIsNY9wt57achppO6JpFzda5KtrAZehKcjMVhETS0CvahYPHQv5/YRG1IDZQnZ5z4I7qFUe6VN/GAYds3QbdYdPyFhFan1qWAeklXfBExac0R6o=,iv:jQi5xRDyYbazpGNYLAeto2GP94LR6cmBzH6EAEmzKwE=,tag:/8Qz04X90pfqw4Z6z0W/OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
