apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
    namespace: slskd
type: Opaque
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:whGs2tY=,iv:zwjJ7lfjrFu37ytqMRBDubBtipuG4nhoY5iBteO3sls=,tag:Y4RexZCHgi2plHwzUWfphQ==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:oGVRZ5Y=,iv:csJYdNxqgsx3oqUBTPLAS8MnaSm/22l/MFwfp9jtD8w=,tag:fqJXCdtvLteJC9Qpp/aiqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIekduN1FMcWFmNFdxa0NV
            eXdqYkRQOUV3K0FnT3Q5WnM3T3c4Wnc0b2hJCmhMT3dvanZvWGF6QXlIcFphUnhZ
            QjZVVFhQd3hwZmVSdTF2UmJsekJJUnMKLS0tIGNreVZTVk1jMmFoZFhvNHhUMEdV
            dTBSVC9qQ25EalRLMlVyaEVCSWpueE0KU/ej6AZOfAjxMvxfprW2m80QS8YdbO+/
            VhrmQlDk35GxfyWdbECmYjN91UB9cKwXqV7TGX+OiYHsEN1zSE6zaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T15:42:17Z"
    mac: ENC[AES256_GCM,data:fBYOf1AthYKFGk4r9vu9cWOyybzlgUXXtUNTz8oRzvIH7lLQ6mrn33qAKXIMgEpU6FFXnALznMO9Z4qzh2KnCYc1hzsvWpTsjJwf3VnTZ/jd+bo3ytBpi8c3TH5EZqVUlcyxJxSxekVwCleCuxaPr5EvaaWEoXKc8tP/slKNQ9Q=,iv:LaUx0i+fJY5FhJlCeEqpR2tkZ3sxX5aNaNMaYsJylBY=,tag:E4MuJzzQOReyVYfba8Q31g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
