apiVersion: v1
kind: Secret
metadata:
    name: slskd-credentials
    namespace: slskd
type: Opaque
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:nltxD2Q=,iv:ua88ufeXdWvargjfZk0JAiiznrY8n1E6ieDPK5a0GCM=,tag:ZfOaIDAr8kyQUSp7r4a08g==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:GtrGVw8=,iv:30EkU5Big0WNsWYnH5OAkcdhCgaqZVWS9QNVhYSRTaU=,tag:QYVSwLOl7uZ4tp2CCa0R6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkpDTStpdVFramtINDdx
            Z094cWt0dTdCeHFiOU52WkV6SFdPNkNUVUVJCjhtZVR5QUpRaHBvTG1pN1F4dlA4
            QWVrOW9Bc0FLRVZDbHA3RWZHMjVJOVEKLS0tIDgyMGdWWHp0Q1Q4cTZEbnBtM0RR
            dFREZ1oxZHM2R0hjZW1uK1M5RDdRckEKJMfpIgbXaPO+9SIHN/mAY8SHxMoY+MX3
            LyFdMIgH5xDLDLybieeCz4+iCizVvJ9ZNjIx5Xbk2swoW7Re1rwuhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T15:31:21Z"
    mac: ENC[AES256_GCM,data:tV0TR7sNljYOTFybm4d/FnmJky9l2SgBBDitpZh+zCUqsvHRB/zFymo6GbSFeBv5vEGuEnsBCOV9f0/oev7/54gIjLnzinlas8Gocj5COib8eFHfc/O3Uqe4oic0y/lD81ewP0sz1V2h2ZldtiOd3rWok1aTraW3r9CK2leMfRY=,iv:+CWGENOpl7J2EvtDDncjz8MenrdnCAESyB+6SQlJ8uQ=,tag:dVaMe4tq57rsQodCps8NNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
