apiVersion: v1
kind: Secret
metadata:
    name: spotify-secret
    namespace: music-server
type: Opaque
stringData:
    SPOTIPY_CLIENT_ID: ENC[AES256_GCM,data:4OCLI2wS5v4v4C2UC/lGx13KYu6I2uUTNlu0Y5Aoy/I=,iv:rn+verCNMjzMAIauh4PT6YV8orbgCoUV5+s0dLh1i9o=,tag:LrTozxHBIFIZi+JLOVfIpg==,type:str]
    SPOTIPY_CLIENT_SECRET: ENC[AES256_GCM,data:5ZS+KwtVTLllw/8x+D3kmZq8/UGiTv5GmEZUHe9jfLo=,iv:Xh32syWTB/vvdfLRI5J/EBbgvZlv6AJfvyhvOleFFNM=,tag:bqJXZAcNSKDF5C9v3f81Bw==,type:str]
sops:
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVJyUXpFa2JRdGkrcWtK
            TVlRUXF2V1JpVHBTc3Y3aEtsRDBoQ0xkbkdjCmFKWU1SQTJ4TGdZUitUVTYrbnNn
            NG5NM0ZocEU5NVJvVHp2aUtQeU1PWVkKLS0tIGhyL1M4SGQ3cU9YaXNBakpOZUk2
            bFRSRTY0dm1nTzdpaklzeW5nMnQ0RWMKloCBbEe1+C74gVfNdSpbyGwcsxQNPsCa
            96ZT7l7QNLumIzFDkc+jPzADIgfrmXyTLgwk5gVWc6kx337+NooyIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T18:37:01Z"
    mac: ENC[AES256_GCM,data:PJTwKxEuCaLf9Z5CMEZ0BhJCdzazGmu3XU09D1CbNIhA4SL5PVGFV6R4JWeKFswWtfj/LFhAFlG3ICFDVK+sJw2fhiTS6UvREMponQUXjLNX2nDMHEG9HQ425Z+wuCKIW9zOrlmMu+lJNcnu5Nue8tPF48YGXp8SwXQe+IHspNM=,iv:0sv8TsjLrsSj63M3cuFVVCvdz5vMw6oYsRLLdPhR3w8=,tag:nS186qep4cwG3ji92c6v8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
