apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:tXtufRY=,iv:butHv+8XzZoMh0/8TbbSu8kJICvHUHVvuetNnVAP5Ns=,tag:5iOPaPQIIjPLXCgk9n4T2w==,type:str]
    password: ENC[AES256_GCM,data:VUYZbihWw751I8VGzIjXFFWgSmTl9hwM6w==,iv:HT5fdQBXywQOnqiWt0P8u2gAIhEenavOCjzVAVJ9f9U=,tag:qA1e6fo8EWEe3YRm/I9Org==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobGFuS0NzQm9DSlV2d1gz
            aE9HU093ODg0QTUyTWJDZ3RiUDFaZGl2Z1Y0ClZKWnlkdGgvbVlKRVFxL0hpT3lY
            WnZxZHNMcEovd0MwbFI0N1hBSkJOZkEKLS0tIFV6aG16TXJ5bVU5RXdhSUZid1lh
            eUl4dUdHdjBLQVE1UDZhSGNHenkydjgKFtPEF/Ilc1e7ADxMsQ68GAkWF464sC9v
            TqQqze7uERsXjo3ff7JGy7BguM1PLnJVf4L7e2JQgwvEsdAB2QpjUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T10:43:29Z"
    mac: ENC[AES256_GCM,data:kIxVkvARrrLyfU6tdnYn0FeL720e26WzjzpKFg5+g623WvLsXShBUKqignMItqsuUMao1dkf+mQNjNLo03OqiUpV0Oo/2eAUpc4KVCo7Yi1pyLruwwe5gCv3Ko1pEMa2Db34Xvysp5/i0s2c29bkdEBY3yaE/21fyjkVTOOQqRc=,iv:3j7aYXiiVZWuCXE93+xPc9wnjivHPdmokJL64qIq5N4=,tag:nWfA5ertWwH91KkyW5UTow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
