apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lrXVhqQGEzDsz7hl8g==,iv:7C0LheIFk/PuCVPtKftaT+DaVuUFUR81Zljf1lN1Kns=,tag:iJFAhL+5R3tPAscZzUSEpA==,type:str]
    password: ENC[AES256_GCM,data:G/KkxX9IVVkDOz0WQdaEV+rqg1i1pDjn9A==,iv:O2aOWNzdQSvoTFOYgW8zh+8yiHtGzID5c6Chycvg4Mw=,tag:PAhR9MHg11c/pxSNogp/0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaU9tb3FZOXdoYXRNUzRn
            ODh6SjNvbTF5WUFqb1ovOXI0Wk5ZWjV5bUZFCkJqcE5QT0JXbGhQRzBjQlJpR0t2
            ZHhPUFVQdHlPaWpRaW8vZ1pOeWppKzAKLS0tIGR5cnVBUEtYUC90UWVKUTYxcGFx
            RXp5ZmQyQmNFbTU4bEFSL2Z1eFRGZ2cKzUSmVc763x4GbGSkGir01RkQrs5u7NMt
            bnCQ8ivSO3PopEQh8EMW3QYndYoduVMd5UOXCQLP0mbIF2YqgBkd+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T10:44:52Z"
    mac: ENC[AES256_GCM,data:qJZOkeqwHoAeC+16V3XCPfxaiiyeKpiWpAJ0z/+dekolX7YeyDAkBcp4IEJeq2ilFDQxvy2GpQ5cOKAAWjkDLEqrCRe5PFnQZ28Jz6CwvhkCQy45AMyiiMGvHTwwXfGLQkirU0/4bUiAzEpH1JJr/q9EB/3bbFwmMlJ+d+U3cyQ=,iv:bKWoX+b4w6DH7RPbWyehgkxbipUGEen179YIxeKIJKU=,tag:5X4EEzJUFuLrhor24qIlXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
