apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Rt1cBMs2o8K6m3ex5Q==,iv:zv3WE1Kx/q4Rl3tMz7b62fN6OmbAjPb2abYMfzUyPtY=,tag:M0ZHg68YW19bu0LWeG83Zw==,type:str]
    password: ENC[AES256_GCM,data:SrYnL0859j6ceibGUeaASdupOnS5FVb+IA==,iv:eF3+CvOUDlZCMVMIMdVOfPbpsS3vOYwxR/6gSBNYpuw=,tag:nAELBSw02LfDqtnsd3Zdmg==,type:str]
    email: ENC[AES256_GCM,data:ylzlD+GPafYWCQMeI4L3L22cb7RUdp0f80Y=,iv:FlQwqJ1phX3hIvyMpvXSmEqZEO28xGxBH1Pj2m/hUlo=,tag:96G7nYBg9JuWVhv7Vxcg/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14smmwkjwd7tjlnlapft5n0msnylr4c2z5dfnvk6pw4rem6jfdsjqy0mgs3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTWJkNWdPb0tDU1VxeVF4
            NmRsdUdZSmhXYzJrQ1IzWHZ3ZFpqVEREb2hVCk5ERElpVHpVcVJPWllZcDhBeGtH
            UFpianVQWEI5OXdEWEZIVFQxSjBpYmcKLS0tIEk2bXV3MmpDMExNVGZudEFXZkFI
            MGJDTXJNaDM0OWg4eXJ1cFVEUzJXbGMKnWl0PGDc+j6DKdQ6VZMwCgV4TE3p9mJn
            L4Is6KkWbIaEMl++/AKXLMO1oT0NATCd1QiYEGR58SIt8ex/T54Npw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T11:54:32Z"
    mac: ENC[AES256_GCM,data:eD/tollJLH+5ac3F/hxfh+2r1IBg7CtxGhoGaqyBs6E/Je/f1SDoNUgth3dgEnQwy2oVqKSZeu87QLuncHoSNxn9Vj8mwGOJ6/200hqH5LTlMsyZ8MXcxgWQlOJakVMyvrrQ69ZztKJ+Ww21tuqMb1ILjGFpeO5l3klbFTFf+Zc=,iv:bitOCDTGX5ZH/oawa6lgep8MPfW4snWatZsB4OQrm/g=,tag:zfaWq+SB35i+D9cWBMlK/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
