apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sunshine
  namespace: flux-system
spec:
  targetNamespace: sunshine
  interval: 10m
  path: ./apps/sunshine
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
